# Generated by Django 4.2.7 on 2024-08-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
